
all:
	cd sched; make  all
	cd master; make  all
	cd client; make  all
	cd demoworker; make all

clean:
	(cd sched; make -e clean)
	(cd master; make -e clean)
	(cd client; make -e clean)
	(cd demoworker; make -e clean)
